import {useCallback,useEffect,useRef,useState} from 'react';
import {fetchStorageLocation,scheduleStorageLocation,cancelStorageLocation,type StorageLocation} from '../../lib/api';
const bytes=(value:number)=>value<1024?`${value} B`:value<1024**2?`${(value/1024).toFixed(1)} KB`:value<1024**3?`${(value/1024**2).toFixed(1)} MB`:`${(value/1024**3).toFixed(2)} GB`;
export default function StorageSettingsCard(){
 const [data,setData]=useState<StorageLocation|null>(null),[path,setPath]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const mounted=useRef(false),pending=useRef(false);
 const load=useCallback(async()=>{if(pending.current)return;pending.current=true;setBusy(true);setError('');try{const value=await fetchStorageLocation();if(mounted.current)setData(value);}catch(e){if(mounted.current)setError(e instanceof Error?e.message:'保存位置读取失败');}finally{pending.current=false;if(mounted.current)setBusy(false);}},[]);
 useEffect(()=>{mounted.current=true;void load();return()=>{mounted.current=false;};},[load]);
 const mutate=async(cancel=false)=>{if(pending.current)return;pending.current=true;setBusy(true);setError('');setNotice('');try{const next=cancel?await cancelStorageLocation():await scheduleStorageLocation(path.trim());if(mounted.current){setData(next);setNotice(cancel?'已取消待生效的迁移计划。':'迁移计划已保存，将在下次启动时执行。');if(!cancel)setPath('');}}catch(e){if(mounted.current)setError(e instanceof Error?e.message:'保存失败');}finally{pending.current=false;if(mounted.current)setBusy(false);}};
 return <section className="storage-settings-card" aria-labelledby="storage-location-title"><div className="storage-settings-heading"><div><h2 id="storage-location-title">内容保存位置</h2><p>选择作品、内容工作记录与参考图片所在的本地文件夹。</p></div><button className="btn btn-sm" disabled={busy} onClick={()=>void load()}>{busy?'读取 / 保存中…':'刷新状态'}</button></div>{error&&<p className="image-error" role="alert">{error}</p>}{notice&&<p className="storage-notice" role="status">{notice}</p>}{data?<><dl className="storage-location-list"><div><dt>当前实际位置</dt><dd>{data.currentPath}</dd></div><div><dt>应用访问位置</dt><dd>{data.logicalPath}</dd></div><div><dt>已保存内容</dt><dd>{data.fileCount.toLocaleString()} 个文件 · {bytes(data.byteCount)}</dd></div><div><dt>状态</dt><dd>{{ready:'可用',pending_restart:'等待下次启动迁移',failed:'迁移失败'}[data.status]}</dd></div>{data.pendingPath&&<div><dt>待生效位置</dt><dd>{data.pendingPath}</dd></div>}{data.backupPath&&<div><dt>保留的备份</dt><dd>{data.backupPath}</dd></div>}</dl>{data.error&&<p className="image-error" role="alert">迁移状态：{data.error}</p>}{data.requiresRestart&&<div className="storage-pending"><strong>重启后生效</strong><p>请先结束正在进行的创作，再关闭并重新启动 Easel。重启前仍使用当前保存位置。</p><button className="btn btn-sm" disabled={busy} onClick={()=>void mutate(true)}>取消待迁移计划</button></div>}<form onSubmit={e=>{e.preventDefault();void mutate();}}><label htmlFor="storage-new-location">新的保存文件夹（绝对路径）</label><input id="storage-new-location" value={path} disabled={busy} onChange={e=>setPath(e.target.value)} placeholder="例如 D:\Easel内容" required/><p className="storage-help">目标须为空目录，由服务端校验。作品、参考图片和工作记录随内容目录迁移；其中临时登录二维码与状态文件也会一同迁移。浏览器会话、持久 Cookie 和模型配置保留在原数据位置。原位置备份会保留供恢复。</p><button className="btn btn-primary" disabled={busy||!path.trim()}>{data.pendingPath?'更新迁移计划':'保存并安排下次启动迁移'}</button></form></>:!error&&<p role="status" className="storage-help">正在读取实际保存位置…</p>}</section>;
}
