import type { AnalysisContent, AnalysisReport, AnalysisTopic } from '../lib/contentAnalysis';
const show=(value:number|null)=>value==null?'缺失':value.toLocaleString('zh-CN',{maximumFractionDigits:2});
const date=(value:string|null)=>value?new Date(value).toLocaleString('zh-CN'):'未提供';
const metrics={views:'播放/阅读次数',likes:'点赞/赞同次数',comments:'评论次数',collects:'收藏次数',shares:'分享次数',impressions:'曝光次数',completions:'完播次数',averageWatchSeconds:'平均观看秒数',durationSeconds:'视频长度秒数',followersAttributed:'归因新增关注',coins:'投币次数',danmaku:'弹幕次数'};
const status={exploratory:'探索性假设',needs_data:'证据不足',editorial:'编辑候选'};
export default function ProfessionalAnalysisPanel({report,busy,onChoose,onPlan,onSave}:{report:AnalysisReport;busy:boolean;onChoose:(content:AnalysisContent)=>void;onPlan:(topic:AnalysisTopic)=>void;onSave:(topic:AnalysisTopic)=>void}) {
 const data=report.professional;
 if(!data)return null;
 const references=(ids:string[])=>ids.map(id=>{const content=report.contents.find(c=>c.id===id);return content?<button type="button" key={id} className="ca-text-button" onClick={()=>onChoose(content)}>{content.title} · {id} →</button>:<span className="ca-caption" key={id}>引用作品 {id} 暂不可用</span>;});
 return <div className="ca-professional">
  <section className="ca-paper" aria-label="当前账号证据范围"><p className="ca-kicker">EVIDENCE / {data.scope.platform} · {data.scope.accountId}</p><h3>这批作品能支持哪些判断</h3><div className="ca-evidence-summary"><div><span>实际样本</span><strong>{data.quality.total} 篇</strong></div><div><span>满足比较条件</span><strong>{data.quality.comparable} 篇</strong></div><div><span>观察起点</span><strong>{date(data.quality.observedFrom)}</strong></div><div><span>最近观察</span><strong>{date(data.quality.observedTo)}</strong></div></div><p className="ca-caption">只比较同平台、同账号、同形式、同窗口、同投放状态与同整日观测年龄。当前样本不代表账号全历史；相关线索不证明算法因果。</p><details><summary>比较组与排除原因</summary>{data.cohorts.length?data.cohorts.map(group=><div key={group.id} className="ca-cohort"><strong>{group.label}</strong><p>{group.contentIds.length} 篇 · {group.period} · 观测年龄 {group.ageDays??'未知'} 天 · {group.format} · {group.paid==null?'投放状态未知':group.paid?'有投放':'无投放'}</p><div className="ca-evidence-links">{references(group.contentIds)}</div></div>):<p className="ca-caption">尚无满足条件的比较组，请补发布时间、窗口、观察时间和投放状态。</p>}{data.quality.excluded.map(item=><p key={item.id}><strong>{report.contents.find(c=>c.id===item.id)?.title||item.id}</strong>：{item.reasons.join('；')}</p>)}</details></section>
  <section className="ca-topic-section" aria-labelledby="ca-topic-heading"><div className="ca-section-intro"><p className="ca-kicker">NEXT TOPIC / 有依据的内容方向</p><h3 id="ca-topic-heading">下一篇可以验证什么题材？</h3><p>候选只来自真实标签与实际评论问题。先核对证据，再选择一项改动；没有爆款分数或流量保证。</p></div>{!data.topics.length?<div className="ca-paper"><p>当前没有可用题材候选。补充至少两篇同主题作品或实际评论问题后重新读取。</p></div>:<div className="ca-topic-grid">{data.topics.map(topic=><article className="ca-paper ca-topic-card" key={topic.id}><div className="ca-card-heading"><span className="ca-evidence-label">{status[topic.status]}</span><span className="ca-caption">引用样本 {topic.sampleCount}/{topic.totalCount}</span></div><h4>{topic.label}</h4><p><strong>实际观察：</strong>{topic.observation}</p><dl className="ca-topic-numbers"><div><dt>比较指标</dt><dd>{topic.metricLabel}</dd></div><div><dt>实验主指标</dt><dd>{metrics[topic.metric]}</dd></div><div><dt>候选 / 比较基线</dt><dd>{show(topic.value)} / {show(topic.baselineValue)}</dd></div><div><dt>窗口与比较条件</dt><dd>{topic.period||"未形成可比窗口"} · {topic.comparison}</dd></div><div><dt>指标缺失作品</dt><dd>{topic.missingCount} 篇</dd></div></dl><p><strong>待验证假设：</strong>{topic.hypothesis}</p><p><strong>只改变一项：</strong>{topic.action}</p><div className="ca-topic-review"><strong>7 天回收计划</strong><p>{date(topic.reviewAt)} · 观察 {metrics[topic.metric]}</p><p>停止规则：{topic.stopRule}</p></div><details><summary>核对引用作品、反例与局限</summary><h5>引用作品</h5><div className="ca-evidence-links">{references(topic.evidenceIds)}</div><h5>同条件对照作品</h5>{topic.counterexampleIds.length?<div className="ca-evidence-links">{references(topic.counterexampleIds)}</div>:<p className="ca-caption">未返回同条件对照，不能判断该题材相对优势或排除其他解释。</p>}<ul>{topic.limitations.map((item,index)=><li key={index}>{item}</li>)}</ul></details><div className="ca-bench-actions"><button type="button" className="btn btn-sm" disabled={busy||!topic.evidenceIds.length} onClick={()=>onSave(topic)}>保存题材与证据</button><button type="button" className="btn btn-primary btn-sm" disabled={busy||!topic.evidenceIds.length} onClick={()=>onPlan(topic)}>预填 7 天实验</button></div></article>)}</div>}</section>
  <details className="ca-paper"><summary>指标定义、单位与公式</summary><div className="ca-metric-definitions">{data.metricDefinitions.map(item=><article key={item.key}><strong>{item.label} · {item.unit}</strong><p>{item.formula}</p><p className="ca-caption">{item.limitation}</p></article>)}</div></details>
 </div>;
}
