import test from 'node:test';
import assert from 'node:assert/strict';
import {Window} from 'happy-dom';
import {act,createElement} from 'react';
import {loadTsModule} from './load-ts.mjs';
globalThis.window=new Window({url:'https://easel.test/'});globalThis.document=window.document;globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const {createRoot}=await import('react-dom/client');const {default:Navigation}=await loadTsModule('../src/components/ChatTurnNavigation.tsx',import.meta.url);
const nodes=[{messageIndex:0,number:1,label:'第一轮的真实请求'},{messageIndex:2,number:2,label:'第二轮补充要求'},{messageIndex:5,number:3,label:'第三轮长请求内容'}];
async function fixture(t,items=nodes){const container=document.createElement('div');document.body.append(container);const root=createRoot(container);const jumps=[];await act(async()=>root.render(createElement(Navigation,{nodes:items,current:1,following:false,onJump:index=>jumps.push(index),onLatest:()=>{}})));t.after(async()=>{await act(async()=>root.unmount());container.remove();});return {container,jumps,ticks:[...container.querySelectorAll('.chat-turn-tick')]};}
test('ticks stay compact, mark current turn and show original request on pointer hover',async t=>{const v=await fixture(t);assert.equal(v.ticks.length,3);assert.equal(v.ticks[1].getAttribute('aria-current'),'step');assert.equal(v.ticks[1].tabIndex,0);assert.equal(v.ticks[0].tabIndex,-1);await act(async()=>v.ticks[0].dispatchEvent(new window.PointerEvent('pointerover',{bubbles:true})));assert.match(v.container.querySelector('[role=tooltip]').textContent,/第一轮的真实请求/);assert.equal(v.ticks[0].getAttribute('aria-describedby'),v.container.querySelector('[role=tooltip]').id);await act(async()=>v.container.querySelector('.chat-turn-ticks').dispatchEvent(new window.PointerEvent('pointerout',{bubbles:true,relatedTarget:document.body})));assert.equal(v.container.querySelector('[role=tooltip]'),null);});
test('keyboard focus previews, arrows roam without jumping and Enter click locates the selected turn',async t=>{const v=await fixture(t);await act(async()=>v.ticks[1].focus());assert.match(v.container.querySelector('[role=tooltip]').textContent,/第二轮补充要求/);await act(async()=>v.ticks[1].dispatchEvent(new window.KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true})));assert.equal(document.activeElement,v.ticks[2]);assert.match(v.container.querySelector('[role=tooltip]').textContent,/第三轮长请求内容/);assert.deepEqual(v.jumps,[]);await act(async()=>v.ticks[2].click());assert.deepEqual(v.jumps,[2]);assert.equal(v.container.querySelector('[role=tooltip]'),null);});
test('Home End and Escape are keyboard reachable and restore compact trigger focus',async t=>{const v=await fixture(t);await act(async()=>v.ticks[1].focus());await act(async()=>document.activeElement.dispatchEvent(new window.KeyboardEvent('keydown',{key:'Home',bubbles:true})));assert.equal(document.activeElement,v.ticks[0]);await act(async()=>document.activeElement.dispatchEvent(new window.KeyboardEvent('keydown',{key:'End',bubbles:true})));assert.equal(document.activeElement,v.ticks[2]);await act(async()=>document.activeElement.dispatchEvent(new window.KeyboardEvent('keydown',{key:'Escape',bubbles:true})));assert.equal(document.activeElement,v.container.querySelector('.chat-turn-nav-trigger'));assert.equal(v.container.querySelector('[role=tooltip]'),null);});
test('a long conversation keeps every node accessible and source labels render as text',async t=>{const items=Array.from({length:120},(_,index)=>({messageIndex:index,number:index+1,label:index===119?'<script>内容只是文本</script>':`真实请求 ${index+1}`}));const v=await fixture(t,items);assert.equal(v.ticks.length,120);await act(async()=>v.ticks[1].focus());await act(async()=>document.activeElement.dispatchEvent(new window.KeyboardEvent('keydown',{key:'End',bubbles:true})));assert.equal(document.activeElement,v.ticks[119]);assert.match(v.container.querySelector('[role=tooltip]').textContent,/<script>内容只是文本<\/script>/);assert.equal(v.container.querySelector('script'),null);});
